# Generated by Django 2.2.3 on 2020-02-06 14:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esfera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Esfera',
                'verbose_name_plural': 'Esferas',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo_lei', models.CharField(choices=[('complementar', 'Lei complementar'), ('ordinaria', 'Lei ordinária'), ('decreto', 'Decreto'), ('portaria', 'Portaria'), ('convenio', 'Convênios Municipais'), ('instrucao', 'Instruções Normativas'), ('outros', 'Outros')], max_length=15, verbose_name='Tipo do documento')),
                ('ano', models.CharField(max_length=4)),
                ('titulo', models.TextField()),
                ('arquivo', models.FileField(upload_to='')),
                ('publicacao', models.DateTimeField(auto_now=True, verbose_name='publicação')),
                ('esfera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lei', to='legislacao.Esfera')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lei', to='legislacao.Secretaria')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Legislação',
                'verbose_name_plural': 'Legislações',
            },
        ),
    ]
