# Generated by Django 2.2.3 on 2020-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='esfera',
            field=models.CharField(choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal')], max_length=15, verbose_name='Esfera'),
        ),
    ]
