# Generated by Django 2.2.3 on 2020-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislacao', '0002_auto_20200206_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Título')),
                ('conteudo', models.TextField()),
                ('data_cria', models.DateTimeField(blank=True, null=True, verbose_name='Data criação')),
                ('data_pub', models.DateField(auto_now=True, null=True)),
                ('publicado', models.BooleanField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='legislacao.Tag')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
