# Generated by Django 2.2.3 on 2020-04-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislacao', '0003_noticia_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
