# Generated by Django 2.2.3 on 2020-04-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUME_PARC', models.CharField(max_length=2, verbose_name='Número da Parcela')),
                ('NUME_TITU', models.CharField(max_length=12, verbose_name='Número do titulo')),
                ('CODI_AGEN', models.CharField(max_length=12, verbose_name='Número da Agencia')),
                ('CODI_AGET', models.CharField(max_length=3, verbose_name='Codigo Agencia')),
                ('SEQU_BDAM', models.CharField(max_length=3, verbose_name='Sequencia Bancaria')),
                ('SEQU_TPAM', models.CharField(max_length=3, verbose_name='Sequencia Tipo AM')),
                ('SEQU_DAM', models.CharField(max_length=6, verbose_name='Sequencia DAM')),
                ('CODI_RECE', models.CharField(max_length=4, verbose_name='Codigo da Receita')),
                ('CODI_TIPO', models.CharField(max_length=4, verbose_name='Codigo Tipo')),
                ('VALO_IMPO', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Imposto')),
                ('BASE_CALC', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Base de Calculo')),
                ('VALO_MULT', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Multa')),
                ('VALO_JURO', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Juros')),
                ('VALO_CORR', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Correção')),
                ('DATA_PAGA', models.DateField(verbose_name='Data Pagamento')),
                ('CODI_TIPA', models.CharField(max_length=2, verbose_name='Codigo tipo')),
                ('DATA_BAIX', models.DateField(verbose_name='Data Baixa')),
                ('MATR_USUA', models.CharField(max_length=5, verbose_name='Matricula Usuário')),
                ('PERI_REFE', models.CharField(max_length=6, verbose_name='Periodo Ref')),
                ('VALO_TOTA', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Total')),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
    ]
