# Generated by Django 2.2.3 on 2020-04-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'managed': True},
        ),
    ]
