# Generated by Django 2.2.3 on 2020-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legado', '0002_auto_20200401_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_titu', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_cont', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_imov', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_pess', models.CharField(blank=True, max_length=255, null=True)),
                ('nume_proc', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_unid', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_rece', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_situ', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('nume_docu', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_moed', models.CharField(blank=True, max_length=255, null=True)),
                ('valo_titu', models.CharField(blank=True, max_length=255, null=True)),
                ('data_lanc', models.CharField(blank=True, max_length=255, null=True)),
                ('peri_refe', models.CharField(blank=True, max_length=255, null=True)),
                ('obse_situ', models.CharField(blank=True, max_length=255, null=True)),
                ('flag_titu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titulos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'managed': False},
        ),
    ]
