# Generated by Django 2.2.3 on 2019-07-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0002_auto_20190707_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroAuto', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='')),
                ('status', models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Recebido', 'Recebido'), ('Processado', 'Processado')], max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='fiscalizacao.Empresa')),
            ],
        ),
    ]
