# Generated by Django 2.2.3 on 2019-11-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacao', '0003_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='arquivo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
